package com.example.hendratay.whatowatch.domain.model

data class MovieDetail(val adult: Boolean,
                       val backdropPath: String?,
                       val belongsToCollection: Any?,
                       val budget: Int,
                       val genres: List<Genre>,
                       val homepage: String?,
                       val id: Int,
                       val imdbId: String?,
                       val originalLangauge: String,
                       val originalTitle: String,
                       val overview: String?,
                       val popularity: Number,
                       val posterPath: String?,
                       val productionCompanies: List<ProductionCompanies>,
                       val productionCountries: List<ProductionCountries>,
                       val releaseDate: String,
                       val revenue: Int,
                       val runtime: Int?,
                       val spokenLanguage: List<SpokenLanguage>,
                       val status: String,
                       val tagline: String?,
                       val title: String,
                       val video: Boolean,
                       val voteAverage: Number,
                       val voteCount: Int)