package com.example.hendratay.whatowatch.domain.model

data class TvDetail(val backdropPath: String?,
                    val createdBy: List<CreatedBy>,
                    val episodeRunTime: List<Int>,
                    val firstAirDate: String,
                    val genres: List<Genres>,
                    val homepage: String,
                    val id: Int,
                    val inProduction: Boolean,
                    val languages: List<String>,
                    val lastAirDate: String,
                    val lastEpisodeToAir: LastEpisodeToAir,
                    val name: String,
                    val networks: List<Networks>,
                    val numberOfEpisodes: Int,
                    val numberOfSeasons: Int,
                    val originCountry: List<String>,
                    val originLanguage: String?,
                    val originName: String?,
                    val overview: String,
                    val popularity: Number,
                    val posterPath: String?,
                    val productionCompanies: List<ProductionCompanies>,
                    val seasons: List<Seasons>,
                    val status: String,
                    val type: String,
                    val voteAverage: Number,
                    val voteCount: Int)