package com.minimalist.moviedb.presentation.model

data class MovieDetailView(val adult: Boolean,
                           val backdropPath: String?,
                           val belongsToCollection: Any?,
                           val budget: Int,
                           val genres: List<GenresView>,
                           val homepage: String?,
                           val id: Int,
                           val imdbId: String?,
                           val originalLanguage: String,
                           val originalTitle: String,
                           val overview: String?,
                           val popularity: Number,
                           val posterPath: String?,
                           val productionCompanies: List<ProductionCompaniesView>,
                           val productionCountries: List<ProductionCountriesView>,
                           val releaseDate: String,
                           val revenue: Int,
                           val runtime: Int?,
                           val spokenLanguages: List<SpokenLanguagesView>,
                           val status: String,
                           val tagline: String?,
                           val title: String,
                           val video: Boolean,
                           val voteAverage: Number,
                           val voteCount: Int)